### ISSUE TITLE
XRechnung UBL PaymentTerms with LineBreak

### ISSUE THREAD

**Issue by quotschmacher** [stephanstapel/ZUGFeRD-csharp#388] opened 2024-10-09 14:14 UTC
Should the UBL-Writer respect Business Rules?

![image](https://github.com/user-attachments/assets/cd5c7e73-3156-4ce5-84ad-a44fc8e885f8)

So it should look like

```
  <cac:PaymentTerms>
    <cbc:Note>
      #SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#
    </cbc:Note>
  </cac:PaymentTerms>
```

and the actual implementation produces:
```
  <cac:PaymentTerms>
    <cbc:Note>#SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#</cbc:Note>
  </cac:PaymentTerms>
```

If I add a verbatim string with line break at the beginning and end, the result looks like
```
  <cac:PaymentTerms>
    <cbc:Note>
#SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#</cbc:Note>
  </cac:PaymentTerms>
```

So the line break at the end is ignored.

Do you think this is a thing? Is the Writer used able to produce this?

**Comment by stephanstapel** [comment] 2024-10-09 15:44
good question. As far as I understand the xml generation capabilities of .net, this is not feasible.
We could implement a dirty way however, inserting a custom string CUSTOMLINEBREAK and replace this value in IInvoiceDescriptorWriter by Environment.NewLine.

Quite a hack. What do you think?

**Comment by quotschmacher** [comment] 2024-10-09 20:58
It is not done with newline I think. The indentation is a thing, too. And this could be multiline given multiple Skonto-terms.
And I am not a friend of such string-replacements ;-) But if it could work...

**Comment by stephanstapel** [comment] 2024-10-14 14:46
I switch to XmlWriter as a base class. I didn't push the change yet, but if you could do this:

![grafik](https://github.com/user-attachments/assets/db69f0d1-bc32-4800-9775-eadfea986fb7)

could you solve the problem mentioned above?

**Comment by quotschmacher** [comment] 2024-10-15 08:19
i am getting the desired result
``` xml
  <cac:PaymentTerms>
    <cbc:Note>
      #SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#
      #SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#
    </cbc:Note>
```

with something like this in the UBL-Writer:
``` csharp
            // PaymentTerms (optional)
            if (this.Descriptor.GetTradePaymentTerms().Where(x => !string.IsNullOrEmpty(x.Description)).ToList().Count > 0)
            {
                Writer.WriteStartElement("cac", "PaymentTerms");                
                var sbPaymentNotes = new StringBuilder();

                Writer.WriteStartElement("cbc", "Note");
                foreach (PaymentTerms paymentTerms in this.Descriptor.GetTradePaymentTerms().Where(x => !string.IsNullOrEmpty(x.Description)))
                {
                    //if (paymentTerms.Description.StartsWith("#") && paymentTerms.Description.EndsWith("#"))
                    {
                        Writer.WriteRawStringWithIndentation(Environment.NewLine);
                        Writer.WriteRawStringWithIndentation(paymentTerms.Description, 6);
                    }
                    //sbPaymentNotes.AppendLine(paymentTerms.Description);
                }
                //Writer.WriteOptionalElementString("cbc", "Note", sbPaymentNotes.ToString().TrimEnd());
                //Writer.WriteRawStringWithIndentation(Environment.NewLine);
                //Writer.WriteRawStringWithIndentation(sbPaymentNotes.ToString(), 6);
                Writer.WriteRawStringWithIndentation(Environment.NewLine);
                Writer.WriteEndElement(4);
            }
```

One new Method in the XML-Writer:
``` csharp
        public void WriteRawStringWithIndentation(string data, int indentation = 0)
        {
            for (int i = 0; i < indentation; i++)
            {
                this.TextWriter?.WriteWhitespace(" ");
            }
            this.TextWriter?.WriteString(data);
        }
```

and extending the WriteEndElement method like this:
``` csharp
        public void WriteEndElement(int indentation = 0)
        {
            StackInfo infoForCurrentXmlLevel = this.XmlStack.Pop();
            if (_DoesProfileFitToCurrentProfile(infoForCurrentXmlLevel.Profile) && _IsNodeVisible())
            {
                for (int i = 0; i < indentation; i++)
                {
                    this.TextWriter?.WriteWhitespace(" ");
                }
                this.TextWriter?.WriteEndElement();
            }
        }
```

But I am not completely happy with it (because of the fixed indentation values) - but it works.

**Comment by stephanstapel** [comment] 2024-10-15 09:28
I agree with your unhappiness :)
Would it be possible to use the XmlStack for indention?
And where is WriteEndElement() put if you don't add indention?

**Comment by stephanstapel** [comment] 2024-10-15 19:45
I guess this is as slick as possible:
https://github.com/stephanstapel/ZUGFeRD-csharp/commit/014e180fe001777851538c41808a78ecc384a35a
Unfortunately it leaves open how to properly indent the closing tag:

![grafik](https://github.com/user-attachments/assets/85dfb58b-68f8-4e60-b822-5937ac8c130e)

How about modifying WriteEndElement() and take into account if the previous line was a raw line?

**Comment by quotschmacher** [comment] 2024-10-16 13:47
So when writing a raw text string setting a private boolean, that then could be evaluated in the WriteEndElement method (newline, indentation) and be reset?

**Comment by stephanstapel** [comment] 2024-10-16 16:39
> So when writing a raw text string setting a private boolean, that then could be evaluated in the WriteEndElement method (newline, indentation) and be reset?

yes, like this. Will do that later.

**Comment by stephanstapel** [comment] 2024-10-16 19:32
Forget about the content, but is this the intended behaviour:

![image](https://github.com/user-attachments/assets/ac6261dd-a26f-40ad-8375-4350aed79b91)

?

**Comment by quotschmacher** [comment] 2024-10-18 13:00
Just tested the CII-export and it is coming out like this (I did not insert it with a linebreak):
``` xml
      <ram:SpecifiedTradePaymentTerms>
        <ram:Description>#SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#
</ram:Description>
      </ram:SpecifiedTradePaymentTerms>
```

But the validator did not say anything about this. So it just does not look very good...

**Comment by stephanstapel** [comment] 2024-10-21 08:35
@quotschmacher : thanks! Could you share the generation code here? I'd like to check if the library can do better.

**Comment by stephanstapel** [comment] 2024-10-22 15:47
@quotschmacher : I have checked in some code and added a test case (UBL only). Can you please check this?

**Comment by quotschmacher** [comment] 2024-10-22 20:07
> @quotschmacher : thanks! Could you share the generation code here? I'd like to check if the library can do better.

no special generation code - simply adding 

``` csharp
result.AddTradePaymentTerms(Invariant($"#SKONTO#TAGE={zahlungsziel}#PROZENT={skonto:F2}#BASISBETRAG={basisbetrag:F2}#"));
```
TradePaymentTerms than than outputting and CII-invoice.

> @quotschmacher : I have checked in some code and added a test case (UBL only). Can you please check this?

I hope I will get it done tomorrow

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:11
Hmm, interesting.
I implemented that output already here:
https://github.com/stephanstapel/ZUGFeRD-csharp/blob/9279a5c66f965a77f5b017dea351f3f2d7e2d6af/ZUGFeRD/InvoiceDescriptor23CIIWriter.cs#L985-L1001

Wouldn't that work for UBL writer?

**Comment by stephanstapel** [comment] 2024-10-25 09:14
> Hmm, interesting. I implemented that output already here:
> 
> https://github.com/stephanstapel/ZUGFeRD-csharp/blob/9279a5c66f965a77f5b017dea351f3f2d7e2d6af/ZUGFeRD/InvoiceDescriptor23CIIWriter.cs#L985-L1001
> 
> Wouldn't that work for UBL writer?

basically yes. The new thing here is correct indention of the node content like here:

https://github.com/stephanstapel/ZUGFeRD-csharp/issues/388#issuecomment-2413207892

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:18
Um, OK. :-)
Not that I would be bothered about indentation as it is XML, and primarily machine-read.

I get the point though, although it is not a technical constraint but optics for the eyes.

Cheers, JoKi

**Comment by stephanstapel** [comment] 2024-10-25 09:22
> Um, OK. :-) Not that I would be bothered about indentation as it is XML, and primarily machine-read.
> 
> I get the point though, although it is not a technical constraint but optics for the eyes. Any XML viewer has a "beautify XML" feature.
> 
> I'd rather would have an option to completely avoid indentation and produces linear, minified XML output. Hence, we have visualizer or renderer to display the XML content for humans.
> 
> Cheers, JoKi

it appeared to be necessary for the validator.

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:32
Nope,

I tested CII output with 2-3 validators online and it passed.
In case of an indentation-focused format like YAML I could understand. However, it's XML and could be without any indentation at all.

Cheers, JoKi

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:35
What I painfully noticed is that the sequence of elements is of importance which led to the weird way of implementation in the CII writer regarding the DueDate.

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:41
Hi, 

> I switch to XmlWriter as a base class for generating XML. I didn't push the change yet, but if you could do this:
> 
> ![grafik](https://github.com/user-attachments/assets/db69f0d1-bc32-4800-9775-eadfea986fb7)
> 
> could you solve the problem mentioned above?

The new line needs to be at the end only. The terminator is "#{Environment. NewLine}".

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:44
> Just tested the CII-export and it is coming out like this (I did not insert it with a linebreak):
> ``` xml
>       <ram:SpecifiedTradePaymentTerms>
>         <ram:Description>#SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=219.80#
> </ram:Description>
>       </ram:SpecifiedTradePaymentTerms>
> ```
> 
> But the validator did not say anything about this. So it just does not look very good...

Exactly, that's the code I contributed. 
The indentation does not matter.

**Comment by jochenkirstaetter** [comment] 2024-10-25 09:54
Something else.

If you take care of the indentation to look good, it would be part of the actual node value.
Meaning, instead of "...#{newline}" the resulting value would include the spaces of the indentation from the next line, and read like this "...#{newline}        " which seems to be more likely problematic than an optical glitch for humans.

**Closed** 2024-10-29 13:13 UTC
